# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pantalla_inicio.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ven_Inicio(object):
    def setupUi(self, ven_Inicio):
        ven_Inicio.setObjectName("ven_Inicio")
        ven_Inicio.resize(571, 423)
        self.centralwidget = QtWidgets.QWidget(ven_Inicio)
        self.centralwidget.setObjectName("centralwidget")
        self.frmPrincipal = QtWidgets.QFrame(self.centralwidget)
        self.frmPrincipal.setGeometry(QtCore.QRect(0, 51, 400, 200))
        self.frmPrincipal.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0.500182, x2:0, y2:0.273, stop:0 rgba(56, 55, 56, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius: 20px;\n"
"border-bottom: 5px solid rgb(98, 97, 98);\n"
"border-right: 5px solid rgb(56, 55, 56);\n"
"border-top: 5px solid rgb(98, 97, 98);\n"
"border-left: 5px solid rgb(98, 97, 98);")
        self.frmPrincipal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmPrincipal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmPrincipal.setObjectName("frmPrincipal")
        self.frmCirculo = QtWidgets.QFrame(self.frmPrincipal)
        self.frmCirculo.setGeometry(QtCore.QRect(20, 17, 401, 400))
        self.frmCirculo.setStyleSheet("background-color:none;\n"
"border: 10px solid rgb(56, 55, 56);\n"
"border-radius: 200px;")
        self.frmCirculo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmCirculo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmCirculo.setObjectName("frmCirculo")
        self.lblBienvenido = QtWidgets.QLabel(self.frmCirculo)
        self.lblBienvenido.setGeometry(QtCore.QRect(10, 122, 371, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.lblBienvenido.setFont(font)
        self.lblBienvenido.setStyleSheet("border-left: none;\n"
"border-top: none;\n"
"border-right: 20px solid rgb(56, 55, 56);\n"
"border-left: 20px solid rgb(56, 55, 56);\n"
"border-radius: 20px;\n"
"border-bottom: 20px solid rgb(56, 55, 56);\n"
"color: rgb(254, 254, 254)")
        self.lblBienvenido.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBienvenido.setObjectName("lblBienvenido")
        self.frame = QtWidgets.QFrame(self.frmCirculo)
        self.frame.setGeometry(QtCore.QRect(97, 26, 211, 41))
        self.frame.setStyleSheet("border:none;\n"
"image: url(:/images/imagenes/estrellas.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frmLogo = QtWidgets.QFrame(self.centralwidget)
        self.frmLogo.setGeometry(QtCore.QRect(320, -10, 250, 261))
        self.frmLogo.setStyleSheet("image: url(:/images/imagenes/taza1.png)")
        self.frmLogo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmLogo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmLogo.setObjectName("frmLogo")
        self.frmBordeLogo = QtWidgets.QFrame(self.centralwidget)
        self.frmBordeLogo.setGeometry(QtCore.QRect(320, 1, 250, 250))
        self.frmBordeLogo.setStyleSheet("border: 7px solid rgb(98, 97, 98);\n"
"border-radius: 20px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0.977, y2:0.0564091, stop:0 rgba(56, 55, 56, 255), stop:1 rgba(98, 97, 98, 133));")
        self.frmBordeLogo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmBordeLogo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmBordeLogo.setObjectName("frmBordeLogo")
        self.frmMasInfo = QtWidgets.QFrame(self.centralwidget)
        self.frmMasInfo.setGeometry(QtCore.QRect(0, 231, 401, 191))
        self.frmMasInfo.setStyleSheet("background-color: rgb(56, 55, 56);\n"
"border-radius: 20px;\n"
"border: 5px solid rgb(98, 97, 98);")
        self.frmMasInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmMasInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmMasInfo.setObjectName("frmMasInfo")
        self.lblDisenador = QtWidgets.QLabel(self.frmMasInfo)
        self.lblDisenador.setGeometry(QtCore.QRect(10, 160, 381, 21))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lblDisenador.setFont(font)
        self.lblDisenador.setStyleSheet("border:none;\n"
"color: rgb(254, 254, 254);")
        self.lblDisenador.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDisenador.setObjectName("lblDisenador")
        self.lblTitulo = QtWidgets.QLabel(self.frmMasInfo)
        self.lblTitulo.setGeometry(QtCore.QRect(10, 50, 381, 21))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(15)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setStyleSheet("border:none;\n"
"color: rgb(254, 254, 254);")
        self.lblTitulo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitulo.setObjectName("lblTitulo")
        self.lblEspere = QtWidgets.QLabel(self.frmMasInfo)
        self.lblEspere.setGeometry(QtCore.QRect(270, 100, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(10)
        self.lblEspere.setFont(font)
        self.lblEspere.setStyleSheet("border:none;\n"
"color: rgb(254, 254, 254);")
        self.lblEspere.setObjectName("lblEspere")
        self.frmBordeLogo.raise_()
        self.frmMasInfo.raise_()
        self.frmPrincipal.raise_()
        self.frmLogo.raise_()
        ven_Inicio.setCentralWidget(self.centralwidget)

        self.retranslateUi(ven_Inicio)
        QtCore.QMetaObject.connectSlotsByName(ven_Inicio)

    def retranslateUi(self, ven_Inicio):
        _translate = QtCore.QCoreApplication.translate
        ven_Inicio.setWindowTitle(_translate("ven_Inicio", "MainWindow"))
        self.lblBienvenido.setText(_translate("ven_Inicio", "BIENVENIDO"))
        self.lblDisenador.setText(_translate("ven_Inicio", "Diseñado por Fonsikay Design"))
        self.lblTitulo.setText(_translate("ven_Inicio", "Inicializando Hotel Spa La Tacita de Plata App"))
        self.lblEspere.setText(_translate("ven_Inicio", "Espere por favor. . . ."))
import imagenes
