# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pantalla_inicio.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from galeria_imagenes import imagen


class ven_Inicio(object):
    def setupUi(self, ven_Inicio):
        ven_Inicio.setObjectName("ven_Inicio")
        ven_Inicio.resize(556, 434)
        self.centralwidget = QtWidgets.QWidget(ven_Inicio)
        self.centralwidget.setObjectName("centralwidget")
        self.frmBordeLogo = QtWidgets.QFrame(self.centralwidget)
        self.frmBordeLogo.setGeometry(QtCore.QRect(325, 1, 231, 191))
        self.frmBordeLogo.setStyleSheet("border: 5px solid rgb(171, 135, 10);\n"
"border-radius: 20px;\n"
"background-color: qlineargradient(spread:pad, x1:0.131, y1:0.347, x2:1, y2:0, stop:0 rgba(227, 192, 69, 192), stop:0.988636 rgba(253, 233, 26, 52));\n"
"\n"
"")
        self.frmBordeLogo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmBordeLogo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmBordeLogo.setObjectName("frmBordeLogo")
        self.frmPrincipal = QtWidgets.QFrame(self.centralwidget)
        self.frmPrincipal.setGeometry(QtCore.QRect(5, 61, 401, 371))
        self.frmPrincipal.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.528, y1:0.858, x2:0.517409, y2:0.159, stop:0 rgba(23, 55, 87, 255), stop:1 rgba(42, 100, 165, 255));\n"
"border-radius: 20px;\n"
"border: 5px solid rgb(171, 135, 10);")
        self.frmPrincipal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmPrincipal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmPrincipal.setObjectName("frmPrincipal")
        self.lblTitulo = QtWidgets.QLabel(self.centralwidget)
        self.lblTitulo.setGeometry(QtCore.QRect(15, 295, 381, 21))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setStyleSheet("border:none;\n"
"color: rgb(32, 76, 123);")
        self.lblTitulo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitulo.setObjectName("lblTitulo")
        self.frmArco = QtWidgets.QFrame(self.centralwidget)
        self.frmArco.setGeometry(QtCore.QRect(-17, 25, 431, 351))
        self.frmArco.setStyleSheet("image: url(:/imagenes/imagenes/arco.png);")
        self.frmArco.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmArco.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmArco.setObjectName("frmArco")
        self.frmEstrella = QtWidgets.QFrame(self.centralwidget)
        self.frmEstrella.setGeometry(QtCore.QRect(74, 114, 261, 91))
        self.frmEstrella.setStyleSheet("border:none;\n"
"image: url(:/imagenes/imagenes/logo_estrella.png);")
        self.frmEstrella.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmEstrella.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmEstrella.setObjectName("frmEstrella")
        self.lblBienvenidos = QtWidgets.QLabel(self.centralwidget)
        self.lblBienvenidos.setGeometry(QtCore.QRect(105, 199, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.lblBienvenidos.setFont(font)
        self.lblBienvenidos.setStyleSheet("color:rgb(245, 245, 245)")
        self.lblBienvenidos.setObjectName("lblBienvenidos")
        self.barra_progreso = QtWidgets.QProgressBar(self.centralwidget)
        self.barra_progreso.setGeometry(QtCore.QRect(29, 350, 191, 22))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.barra_progreso.setFont(font)
        self.barra_progreso.setStyleSheet("QProgressBar\n"
"{\n"
"    background-color :rgb(227, 192, 69);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"    color: rgb(254, 254, 254);\n"
"}\n"
"\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color:qlineargradient(spread:pad, x1:0.528, y1:0.858, x2:0.517409, y2:0.159, stop:0 rgba(23, 55, 87, 255), stop:1 rgba(42, 100, 165, 255));\n"
"    border-radius: 5px;\n"
"}")
        self.barra_progreso.setProperty("value", 0)
        self.barra_progreso.setObjectName("barra_progreso")
        self.lblDisenador = QtWidgets.QLabel(self.centralwidget)
        self.lblDisenador.setGeometry(QtCore.QRect(15, 400, 381, 21))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lblDisenador.setFont(font)
        self.lblDisenador.setStyleSheet("border:none;\n"
"color: rgb(32, 76, 123);")
        self.lblDisenador.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDisenador.setObjectName("lblDisenador")
        self.lblEstado = QtWidgets.QLabel(self.centralwidget)
        self.lblEstado.setGeometry(QtCore.QRect(228, 352, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(10)
        self.lblEstado.setFont(font)
        self.lblEstado.setStyleSheet("border:none;\n"
"color: rgb(32, 76, 123);")
        self.lblEstado.setAlignment(QtCore.Qt.AlignCenter)
        self.lblEstado.setWordWrap(True)
        self.lblEstado.setObjectName("lblEstado")
        self.frmColorMasInfo = QtWidgets.QFrame(self.centralwidget)
        self.frmColorMasInfo.setGeometry(QtCore.QRect(5, 267, 401, 165))
        self.frmColorMasInfo.setStyleSheet("background-color: rgb(227, 192, 69);\n"
"border-bottom-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;\n"
"border: 5px solid rgb(171, 135, 10);")
        self.frmColorMasInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmColorMasInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmColorMasInfo.setObjectName("frmColorMasInfo")
        self.frmLogo = QtWidgets.QFrame(self.centralwidget)
        self.frmLogo.setGeometry(QtCore.QRect(330, 10, 221, 171))
        self.frmLogo.setStyleSheet("image: url(:/imagenes/imagenes/logo.png);")
        self.frmLogo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmLogo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmLogo.setObjectName("frmLogo")
        self.frmBordeLogo.raise_()
        self.frmPrincipal.raise_()
        self.lblBienvenidos.raise_()
        self.frmEstrella.raise_()
        self.frmColorMasInfo.raise_()
        self.frmArco.raise_()
        self.lblDisenador.raise_()
        self.lblEstado.raise_()
        self.lblTitulo.raise_()
        self.barra_progreso.raise_()
        self.frmLogo.raise_()
        ven_Inicio.setCentralWidget(self.centralwidget)

        self.retranslateUi(ven_Inicio)
        QtCore.QMetaObject.connectSlotsByName(ven_Inicio)

    def retranslateUi(self, ven_Inicio):
        _translate = QtCore.QCoreApplication.translate
        ven_Inicio.setWindowTitle(_translate("ven_Inicio", "MainWindow"))
        self.lblTitulo.setText(_translate("ven_Inicio", "Inicializando Hotel Spa La Tacita de Plata App"))
        self.lblBienvenidos.setText(_translate("ven_Inicio", "BIENVENIDO"))
        self.lblDisenador.setText(_translate("ven_Inicio", "Diseñado por Fonsikay Design"))
        self.lblEstado.setText(_translate("ven_Inicio", "Espere por favor. . . ."))

