# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pantalla_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from galeria_imagenes import icono


class venPrincipal(object):
    def setupUi(self, venPrincipal):
        venPrincipal.setObjectName("venPrincipal")
        venPrincipal.resize(1187, 564)
        venPrincipal.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(venPrincipal)
        self.centralwidget.setStyleSheet("/* ------------------------- SECCIONES DE LA APLICACION --------------------------*/\n"
"\n"
"/* Color de fondo de las secciones */\n"
"QFrame#frmCabecera, #frmBotonera, #frmMenu, #frmMenuDer, #frmMenuIzq, #frmBarraEstado\n"
"{\n"
"    background-color:qlineargradient(spread:pad, x1:0.528, y1:0.858,                         x2:0.517409, y2:0.159, stop:0 rgba(23, 55, 87, 255), stop:1 rgba(42, 100,             165, 255));\n"
"}\n"
"\n"
"/* --------------- SECCIÓN DE LA CABECERA DE LA APLICACION -----------------*/\n"
"\n"
"/* Color de la linea inferior */\n"
"QFrame#frmCabecera\n"
"{\n"
"border-bottom: 1px solid rgb(171, 135, 10);\n"
"}\n"
"\n"
"/* - SECCIÓN DE LA BOTONERA DE MENU E ICONO DE LA BARRA DE TITULO -*/\n"
"\n"
"/* Se elimina los bordes */\n"
"QFrame#frmMenu \n"
"{\n"
"    border-bottom: none;\n"
"}\n"
"\n"
"/* Color del botón Minimizar cuando se posiciona el cursor */\n"
"QPushButton#btnMenu:hover\n"
"{\n"
"      background-color:qlineargradient(spread:pad, x1:0.528409, y1:0.733,                     x2:0.5, y2:0.17, stop:0 #b28d0b, stop:1 #f5cc3d);\n"
"}\n"
"\n"
"/* Color del botón Minimizar cuando se pulsa el botón */\n"
"QPushButton#btnMenu:pressed\n"
"{\n"
"  \n"
"    background-color: #b28d0b\n"
"}\n"
"\n"
"/* Imágen de la barra de título */\n"
"QFrame#frmLogo\n"
"{\n"
"    image: url(:/imagenes/imagenes/logo.png);\n"
"    border:none;\n"
"}\n"
"\n"
"/* Titulo de la barra de título */\n"
"QLabel#lblLogo\n"
"{\n"
"    color: rgb(198, 160, 30);\n"
"    font: 25 18pt \"Gabriola\";\n"
"}\n"
"\n"
"/* ------------ SECCIÓN DE LA BOTONERA DE LA BARRA DE TITULO -------------*/\n"
"\n"
"/* Color de la botonera de la barra de título */\n"
"QPushButton#btnMinimizar, #btnMaximizar, #btnCerrar, #btnMenu\n"
"{\n"
"    border: 1px solid rgb(171, 135, 10);\n"
"    border-radius: 13px;\n"
"}\n"
"\n"
"/* Color del botón Minimizar cuando se posiciona el cursor */\n"
"QPushButton#btnMinimizar:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0,             stop:0 #2eae35, stop:1 #cae44a);\n"
"}\n"
"\n"
"/* Color del botón Minimizar cuando se pulsa el botón */\n"
"QPushButton#btnMinimizar:pressed \n"
"{\n"
"    background-color: #2eae35;\n"
"}\n"
"\n"
"/* Color del botón Maximizar cuando se posiciona el cursor */\n"
"QPushButton#btnMaximizar:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0,             stop:0 #FF7100, stop:1 #FFDB34);\n"
"}\n"
"\n"
"/* Color del botón Maximizar cuando se pulsa el botón */\n"
"QPushButton#btnMaximizar:pressed \n"
"{\n"
"    background-color: #FF7100;\n"
"}\n"
"\n"
"/* Color del botón Cerrar cuando se posiciona el cursor */\n"
"QPushButton#btnCerrar:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0,             stop:0 #95050d, stop:1 #ea0a20);\n"
"}\n"
"\n"
"/* Color del botón Cerrar cuando se pulsa el botón */\n"
"QPushButton#btnCerrar:pressed \n"
"{\n"
"    background-color: #95050d;\n"
"}\n"
"\n"
"/* --------------------- SECCIÓN DEL CUERPO DE LA VENTANA ---------------------*/\n"
"\n"
"/* Se elimina los bordes */\n"
"QFrame#frmCuerpo \n"
"{\n"
"    border:none;\n"
"}\n"
"\n"
"/* ---------------- SECCIÓN DE LA BARRA DE MENÚ IZQUIERDA ------------------ */\n"
"\n"
"/* Se elimina los bordes de la sección del menú menos el derecho que se indica con el color dorado */\n"
"QFrame#frmMenuIzq\n"
"{\n"
"    border-left: none;\n"
"    border-top: none;\n"
"    border-bottom: none;\n"
"    border-right: 1px solid #b28d0b;\n"
"}\n"
"/* Estilo de los botones del menú izquierdo */\n"
"QPushButton#btnInicio, #btnCuenta, #btnAjustes\n"
"{\n"
"    border-left: none;\n"
"    border-top: none;\n"
"    border-right: none;\n"
"    color: #ffffff;\n"
"    padding-left: 60px;\n"
"    padding-top: 10px;\n"
"    padding-bottom: 10px;\n"
"    font: 25 13pt \"Bahnschrift Light\";\n"
"    background-repeat: none;\n"
"    text-align: left;\n"
"    background-position: center left;\n"
"}\n"
"\n"
"/* Borde inferior en los botones */\n"
"QPushButton#btnInicio, #btnCuenta\n"
"{\n"
"    border-bottom: 1px solid rgb(171, 135, 10);\n"
"}\n"
"\n"
"/* Borde superior en el boton */\n"
"QPushButton#btnAjustes\n"
"{\n"
"    border-top: 1px solid rgb(171, 135, 10);\n"
"}\n"
"\n"
"/* Color del botón Minimizar cuando se posiciona el cursor */\n"
"QPushButton#btnInicio:hover, #btnCuenta:hover, #btnAjustes:hover\n"
"{\n"
"      background-color:qlineargradient(spread:pad, x1:0.528409, y1:0.733,                     x2:0.5, y2:0.17, stop:0 #b28d0b, stop:1 #f5cc3d);\n"
"}\n"
"\n"
"/* Color del botón Minimizar cuando se pulsa el botón */\n"
"QPushButton#btnInicio:pressed, #btnCuenta:pressed, #btnAjustes:pressed\n"
"{\n"
"  \n"
"    background-color: #b28d0b\n"
"}\n"
"\n"
"/* Icono para el botón Inicio */\n"
"QPushButton#btnInicio\n"
"{\n"
"background-image: url(:/iconos/iconos/cil-home2.png);\n"
"}\n"
"\n"
"/* Icono para el botón Cuenta */\n"
"QPushButton#btnCuenta\n"
"{\n"
"background-image: url(:/iconos/iconos/cil-user2.png);\n"
"}\n"
"\n"
"/* Icono para el botón Ajustes */\n"
"QPushButton#btnAjustes\n"
"{\n"
"background-image: url(:/iconos/iconos/cil-settings2.png);\n"
"}\n"
"\n"
"/* ------------------ SECCIÓN DE LA BARRA DE MENÚ DERECHA ------------------ */\n"
"\n"
"/* Color del borde izquierdo */\n"
"QFrame#frmMenuDer\n"
"{ \n"
"    border-left: 1px solid rgb(171, 135, 10);\n"
"}\n"
"\n"
"/* --------------------- SECCIÓN DEL CUERPO DE LA VENTANA -------------------- */\n"
"\n"
"/* Se elimina los bordes */\n"
"QFrame#frmCuerpo \n"
"{\n"
"    border:none;\n"
"}\n"
"\n"
"/* ----------------------- SECCIÓN CENTRAL DE CONTENIDO ---------------------- */\n"
"\n"
"/* Color de fondo de la sección */\n"
"QFrame#frmContenido \n"
"{\n"
"    background-color: rgb(240, 240, 240);\n"
"}\n"
"\n"
"/* --------------------------- SECCIÓN BARRA DE ESTADO -------------------------- */\n"
"\n"
"/* Color del borde superior */\n"
"QFrame#frmBarraEstado\n"
"{ \n"
"    border-top: 1px solid rgb(171, 135, 10);\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frmCabecera = QtWidgets.QFrame(self.centralwidget)
        self.frmCabecera.setMaximumSize(QtCore.QSize(16777215, 43))
        self.frmCabecera.setStyleSheet("")
        self.frmCabecera.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmCabecera.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmCabecera.setObjectName("frmCabecera")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frmCabecera)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frmTituloContenedor = QtWidgets.QFrame(self.frmCabecera)
        self.frmTituloContenedor.setStyleSheet("")
        self.frmTituloContenedor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmTituloContenedor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmTituloContenedor.setObjectName("frmTituloContenedor")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frmTituloContenedor)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frmMenu = QtWidgets.QFrame(self.frmTituloContenedor)
        self.frmMenu.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frmMenu.setStyleSheet("")
        self.frmMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmMenu.setObjectName("frmMenu")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frmMenu)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnMenu = QtWidgets.QPushButton(self.frmMenu)
        self.btnMenu.setMinimumSize(QtCore.QSize(0, 0))
        self.btnMenu.setMaximumSize(QtCore.QSize(30, 26))
        self.btnMenu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMenu.setStyleSheet("")
        self.btnMenu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconos/iconos/cil-menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMenu.setIcon(icon)
        self.btnMenu.setIconSize(QtCore.QSize(16, 16))
        self.btnMenu.setObjectName("btnMenu")
        self.horizontalLayout_4.addWidget(self.btnMenu)
        self.horizontalLayout_5.addWidget(self.frmMenu)
        self.frmTitulo = QtWidgets.QFrame(self.frmTituloContenedor)
        self.frmTitulo.setStyleSheet("")
        self.frmTitulo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmTitulo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmTitulo.setObjectName("frmTitulo")
        self.frmLogo = QtWidgets.QFrame(self.frmTitulo)
        self.frmLogo.setGeometry(QtCore.QRect(8, -4, 51, 41))
        self.frmLogo.setStyleSheet("")
        self.frmLogo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmLogo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmLogo.setObjectName("frmLogo")
        self.lblLogo = QtWidgets.QLabel(self.frmTitulo)
        self.lblLogo.setGeometry(QtCore.QRect(68, 2, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.lblLogo.setFont(font)
        self.lblLogo.setWordWrap(False)
        self.lblLogo.setObjectName("lblLogo")
        self.horizontalLayout_5.addWidget(self.frmTitulo)
        self.horizontalLayout_2.addWidget(self.frmTituloContenedor)
        self.frmBotonera = QtWidgets.QFrame(self.frmCabecera)
        self.frmBotonera.setMaximumSize(QtCore.QSize(105, 16777215))
        self.frmBotonera.setStyleSheet("")
        self.frmBotonera.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmBotonera.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmBotonera.setObjectName("frmBotonera")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frmBotonera)
        self.horizontalLayout_3.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnMinimizar = QtWidgets.QPushButton(self.frmBotonera)
        self.btnMinimizar.setMaximumSize(QtCore.QSize(30, 26))
        self.btnMinimizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMinimizar.setStyleSheet("")
        self.btnMinimizar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/iconos/iconos/cil-window-minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMinimizar.setIcon(icon1)
        self.btnMinimizar.setIconSize(QtCore.QSize(16, 16))
        self.btnMinimizar.setObjectName("btnMinimizar")
        self.horizontalLayout_3.addWidget(self.btnMinimizar)
        self.btnMaximizar = QtWidgets.QPushButton(self.frmBotonera)
        self.btnMaximizar.setMaximumSize(QtCore.QSize(30, 26))
        self.btnMaximizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMaximizar.setStyleSheet("")
        self.btnMaximizar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/iconos/iconos/cil-window-restore.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMaximizar.setIcon(icon2)
        self.btnMaximizar.setIconSize(QtCore.QSize(16, 16))
        self.btnMaximizar.setObjectName("btnMaximizar")
        self.horizontalLayout_3.addWidget(self.btnMaximizar)
        self.btnCerrar = QtWidgets.QPushButton(self.frmBotonera)
        self.btnCerrar.setMaximumSize(QtCore.QSize(30, 26))
        self.btnCerrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCerrar.setStyleSheet("")
        self.btnCerrar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/iconos/iconos/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCerrar.setIcon(icon3)
        self.btnCerrar.setIconSize(QtCore.QSize(16, 16))
        self.btnCerrar.setObjectName("btnCerrar")
        self.horizontalLayout_3.addWidget(self.btnCerrar)
        self.horizontalLayout_2.addWidget(self.frmBotonera)
        self.verticalLayout.addWidget(self.frmCabecera)
        self.frmCuerpo = QtWidgets.QFrame(self.centralwidget)
        self.frmCuerpo.setStyleSheet("")
        self.frmCuerpo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmCuerpo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmCuerpo.setObjectName("frmCuerpo")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frmCuerpo)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frmMenuIzq = QtWidgets.QFrame(self.frmCuerpo)
        self.frmMenuIzq.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frmMenuIzq.setStyleSheet("")
        self.frmMenuIzq.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmMenuIzq.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmMenuIzq.setLineWidth(0)
        self.frmMenuIzq.setObjectName("frmMenuIzq")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frmMenuIzq)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frmBotonesTop = QtWidgets.QFrame(self.frmMenuIzq)
        self.frmBotonesTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmBotonesTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmBotonesTop.setObjectName("frmBotonesTop")
        self.formLayout = QtWidgets.QFormLayout(self.frmBotonesTop)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.btnInicio = QtWidgets.QPushButton(self.frmBotonesTop)
        self.btnInicio.setMinimumSize(QtCore.QSize(140, 0))
        self.btnInicio.setObjectName("btnInicio")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.btnInicio)
        self.btnCuenta = QtWidgets.QPushButton(self.frmBotonesTop)
        self.btnCuenta.setMinimumSize(QtCore.QSize(140, 0))
        self.btnCuenta.setObjectName("btnCuenta")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.btnCuenta)
        self.verticalLayout_2.addWidget(self.frmBotonesTop)
        self.btnAjustes = QtWidgets.QPushButton(self.frmMenuIzq)
        self.btnAjustes.setMinimumSize(QtCore.QSize(140, 0))
        self.btnAjustes.setObjectName("btnAjustes")
        self.verticalLayout_2.addWidget(self.btnAjustes)
        self.horizontalLayout.addWidget(self.frmMenuIzq)
        self.frmContenido = QtWidgets.QFrame(self.frmCuerpo)
        self.frmContenido.setStyleSheet("")
        self.frmContenido.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmContenido.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmContenido.setObjectName("frmContenido")
        self.horizontalLayout.addWidget(self.frmContenido)
        self.frmMenuDer = QtWidgets.QFrame(self.frmCuerpo)
        self.frmMenuDer.setMaximumSize(QtCore.QSize(127, 16777215))
        self.frmMenuDer.setStyleSheet("")
        self.frmMenuDer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmMenuDer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmMenuDer.setObjectName("frmMenuDer")
        self.horizontalLayout.addWidget(self.frmMenuDer)
        self.verticalLayout.addWidget(self.frmCuerpo)
        self.frmBarraEstado = QtWidgets.QFrame(self.centralwidget)
        self.frmBarraEstado.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frmBarraEstado.setStyleSheet("")
        self.frmBarraEstado.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmBarraEstado.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmBarraEstado.setObjectName("frmBarraEstado")
        self.verticalLayout.addWidget(self.frmBarraEstado)
        venPrincipal.setCentralWidget(self.centralwidget)

        self.retranslateUi(venPrincipal)
        QtCore.QMetaObject.connectSlotsByName(venPrincipal)

    def retranslateUi(self, venPrincipal):
        _translate = QtCore.QCoreApplication.translate
        venPrincipal.setWindowTitle(_translate("venPrincipal", "MainWindow"))
        self.lblLogo.setText(_translate("venPrincipal", "Hotel Spa La Tacita de Plata"))
        self.btnInicio.setText(_translate("venPrincipal", "Inicio"))
        self.btnCuenta.setText(_translate("venPrincipal", "Cuenta"))
        self.btnAjustes.setText(_translate("venPrincipal", "Ajustes"))
